2022-06-24 12:41:35 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-06-24 12:41:35 NumExpr defaulting to 8 threads.
2022-06-24 12:41:37 Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2022-06-24 12:41:37 Creating converter from 7 to 5
2022-06-24 12:41:37 Creating converter from 5 to 7
2022-06-24 12:41:37 Creating converter from 7 to 5
2022-06-24 12:41:37 Creating converter from 5 to 7
2022-06-24 12:41:39 addr2: cardinality : 74 and embedding dim: 37
2022-06-24 12:41:39 id_06: cardinality : 103 and embedding dim: 51
2022-06-24 12:41:39 id_33: cardinality : 262 and embedding dim: 100
2022-06-24 12:41:39 M4: cardinality : 5 and embedding dim: 2
2022-06-24 12:41:39 DeviceInfo: cardinality : 1788 and embedding dim: 100
2022-06-24 12:41:39 id_25: cardinality : 343 and embedding dim: 100
2022-06-24 12:41:39 id_22: cardinality : 27 and embedding dim: 13
2022-06-24 12:41:39 card4: cardinality : 6 and embedding dim: 3
2022-06-24 12:41:39 id_31: cardinality : 132 and embedding dim: 66
2022-06-24 12:41:39 id_26: cardinality : 97 and embedding dim: 48
2022-06-24 12:41:39 id_32: cardinality : 6 and embedding dim: 3
2022-06-24 12:41:39 id_01: cardinality : 78 and embedding dim: 39
2022-06-24 12:41:40 card1: cardinality : 8500 and embedding dim: 100
2022-06-24 12:41:40 id_04: cardinality : 17 and embedding dim: 8
2022-06-24 12:41:40 id_08: cardinality : 96 and embedding dim: 48
2022-06-24 12:41:40 R_emaildomain: cardinality : 62 and embedding dim: 31
2022-06-24 12:41:40 id_05: cardinality : 95 and embedding dim: 47
2022-06-24 12:41:40 id_24: cardinality : 14 and embedding dim: 7
2022-06-24 12:41:40 id_15: cardinality : 5 and embedding dim: 2
2022-06-24 12:41:40 ProductCD: cardinality : 5 and embedding dim: 2
2022-06-24 12:41:40 id_23: cardinality : 5 and embedding dim: 2
2022-06-24 12:41:40 id_13: cardinality : 56 and embedding dim: 28
2022-06-24 12:41:40 id_17: cardinality : 106 and embedding dim: 53
2022-06-24 12:41:40 card2: cardinality : 484 and embedding dim: 100
2022-06-24 12:41:40 card5: cardinality : 108 and embedding dim: 54
2022-06-24 12:41:40 id_10: cardinality : 64 and embedding dim: 32
2022-06-24 12:41:40 id_03: cardinality : 26 and embedding dim: 13
2022-06-24 12:41:40 id_07: cardinality : 86 and embedding dim: 43
2022-06-24 12:41:40 id_14: cardinality : 27 and embedding dim: 13
2022-06-24 12:41:40 id_18: cardinality : 20 and embedding dim: 10
2022-06-24 12:41:40 id_19: cardinality : 524 and embedding dim: 100
2022-06-24 12:41:40 card6: cardinality : 5 and embedding dim: 2
2022-06-24 12:41:40 id_21: cardinality : 492 and embedding dim: 100
2022-06-24 12:41:40 id_30: cardinality : 77 and embedding dim: 38
2022-06-24 12:41:40 id_34: cardinality : 6 and embedding dim: 3
2022-06-24 12:41:40 card3: cardinality : 105 and embedding dim: 52
2022-06-24 12:41:40 id_20: cardinality : 396 and embedding dim: 100
2022-06-24 12:41:40 id_09: cardinality : 48 and embedding dim: 24
2022-06-24 12:41:40 id_11: cardinality : 367 and embedding dim: 100
2022-06-24 12:41:40 addr1: cardinality : 257 and embedding dim: 100
2022-06-24 12:41:40 P_emaildomain: cardinality : 61 and embedding dim: 30
2022-06-24 12:41:40 None
2022-06-24 12:42:04 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:42:06 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:42:25 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:42:28 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:42:40 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:42:46 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:42:48 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:43:07 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:43:09 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:43:28 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:43:29 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:43:41 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:43:49 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:43:51 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:44:10 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:44:12 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:44:31 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:44:33 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:44:51 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:44:53 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:45:12 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:45:14 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:45:33 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:45:35 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:45:54 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:45:56 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:46:16 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:46:18 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:46:37 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:46:39 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:46:58 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:47:00 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:47:18 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:47:21 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:47:40 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:47:42 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:48:01 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:48:03 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:48:23 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:48:25 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:48:43 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:48:45 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:49:06 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:49:08 Only one class present in y_true. ROC AUC score is not defined in that case.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tmpv1ks3aro.py", line 19, in fallback_auc
    retval__1 = ag__.converted_call(ag__.ld(roc_auc_score), (ag__.ld(y_true_), ag__.ld(y_pred_)), None, fscope_1)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 464, in _call_unconverted
    return f(*args)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 569, in roc_auc_score
    return _average_binary_score(
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\user\anaconda3\envs\tf_gpu\lib\site-packages\sklearn\metrics\_ranking.py", line 338, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
2022-06-24 12:49:09 addr2 dim: 37
2022-06-24 12:49:09 id_06 dim: 51
2022-06-24 12:49:09 id_33 dim: 100
2022-06-24 12:49:09 M4 dim: 2
2022-06-24 12:49:09 DeviceInfo dim: 100
2022-06-24 12:49:09 id_25 dim: 100
2022-06-24 12:49:09 id_22 dim: 13
2022-06-24 12:49:09 card4 dim: 3
2022-06-24 12:49:09 id_31 dim: 66
2022-06-24 12:49:09 id_26 dim: 48
2022-06-24 12:49:09 id_32 dim: 3
2022-06-24 12:49:09 id_01 dim: 39
2022-06-24 12:49:09 card1 dim: 100
2022-06-24 12:49:09 id_04 dim: 8
2022-06-24 12:49:09 id_08 dim: 48
2022-06-24 12:49:09 R_emaildomain dim: 31
2022-06-24 12:49:09 id_05 dim: 47
2022-06-24 12:49:09 id_24 dim: 7
2022-06-24 12:49:09 id_15 dim: 2
2022-06-24 12:49:09 ProductCD dim: 2
2022-06-24 12:49:09 id_23 dim: 2
2022-06-24 12:49:09 id_13 dim: 28
2022-06-24 12:49:09 id_17 dim: 53
2022-06-24 12:49:09 card2 dim: 100
2022-06-24 12:49:09 card5 dim: 54
2022-06-24 12:49:09 id_10 dim: 32
2022-06-24 12:49:09 id_03 dim: 13
2022-06-24 12:49:09 id_07 dim: 43
2022-06-24 12:49:09 id_14 dim: 13
2022-06-24 12:49:09 id_18 dim: 10
2022-06-24 12:49:09 id_19 dim: 100
2022-06-24 12:49:09 card6 dim: 2
2022-06-24 12:49:09 id_21 dim: 100
2022-06-24 12:49:09 id_30 dim: 38
2022-06-24 12:49:09 id_34 dim: 3
2022-06-24 12:49:09 card3 dim: 52
2022-06-24 12:49:09 id_20 dim: 100
2022-06-24 12:49:09 id_09 dim: 24
2022-06-24 12:49:09 id_11 dim: 100
2022-06-24 12:49:09 addr1 dim: 100
2022-06-24 12:49:09 P_emaildomain dim: 30
2022-06-24 12:49:09 Transforming categorical features
